### PR TITLE
Fixed API.Manager.Summon

### PR DESCRIPTION
**Pull request by ImIsaacTbh**
werent running it as coroutine

### CODE REVIEW

**Comment by ImIsaacTbh** [comment]
did slight retard moment again with the prints but all good now

**Review by FoxWorn3365 — CHANGES_REQUESTED** [review]
You should remove the `.csprpj` as is in conflict with ours and from the `Manager.cs` there's 
```csharp
using PluginAPI.Core;
```
who's not needed

**Comment by ImIsaacTbh** [comment]
yeah i was getting constant build errors without changing the c# version to 9 so i thought i might aswell leave it in

**Comment by FoxWorn3365** [comment]
Remove the `PluginAPI.Core` and the PR will be fine

**Comment by FoxWorn3365** [comment]
I'm so stupid, you need to readd the .csproj but make sure to copy it fron the main branch of the plugin

**Comment by FoxWorn3365** [comment]
unactive

**Pull request closed without merging**
